using System.Data;
using System.Xml.Serialization;

/// <remarks/>
/// <remarks/>

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

namespace Ferc549DBusiness.XsdClasses {
  using Ferc549DBusiness.XsdClasses;
  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ferc.gov/549D.xsd")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://ferc.gov/549D.xsd", IsNullable = false)]
  public partial class form1 {

    /// <remarks/>
    public form1RESPONDENT RESPONDENT;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("SDSet", IsNullable = false)]
    public form1SDSet[] SHIPDATA;

    public static form1 GetForm1WithProvidedDataRows(DataRow[] rows) {
      return new form1() { RESPONDENT = form1RESPONDENT.GetForm1Respondent(rows), SHIPDATA = form1SDSet.GetForm1SDSet(rows) };
    }
  }
}